std = "roblox"

[lints]
almost_swapped = "warn"
constant_table_comparison = "warn"
deprecated = "warn"
divide_by_zero = "deny"
duplicate_keys = "deny"
empty_if = "warn"
empty_loop = "warn"
global_usage = "warn"
high_cyclomatic_complexity = "allow"
if_same_then_else = "warn"
ifs_same_cond = "warn"
incorrect_standard_library_use = "deny"
manual_table_clone = "warn"
mismatched_arg_count = "deny"
mixed_table = "warn"
multiple_statements = "allow"
must_use = "warn"
parenthese_conditions = "warn"
shadowing = "warn"
suspicious_reverse_loop = "warn"
type_check_inside_call = "warn"
unbalanced_assignments = "deny"
undefined_variable = "deny"
unscoped_variables = "deny"
unused_variable = "warn"